services:
  insa-utils:
    image: richarvey/nginx-php-fpm:latest
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.host: insa-utils.fr
    environment:
      TZ: Europe/Paris
      VPN_USER: cgrennerat@insa-lyon.fr
      VPN_PASSWORD: $VPN_PASSWORD
      MEILISEARCH_HOST: meilisearch
      MEILISEARCH_PORT: 7700
      MEILISEARCH_KEY: $MEILISEARCH_KEY
      SMTP_HOST: postal.clgr.io
      SMTP_PORT: 25
      SMTP_FROM_EMAIL: auth@insa-utils.fr
      SMTP_FROM_NAME: 'INSA Utils'
      SMTP_USERNAME: clgr-services/insa-utils
      SMTP_PASSWORD: $SMTP_PASSWORD
      DB_HOST: mysql
      DB_PASSWORD: $DB_PASSWORD
      WEBPUSH_PRIVATE_KEY: $WEBPUSH_PRIVATE_KEY

      RUN_SCRIPTS: 1
      REAL_IP_HEADER: 1
      REAL_IP_FROM: 172.26.0.2/32
      GIT_PERSONAL_TOKEN: $GIT_PERSONAL_TOKEN
      GIT_USERNAME: ClementGre
      GIT_REPO: 'github.com/ClementGre/insa-utils.git'
      GIT_EMAIL: 'me@clgr.io'
      GIT_NAME: 'Clément Grennerat'
    networks:
      - traefik
      - mysql
      - insa-utils
    volumes:
      - /home/clement/openconnect/openconnect-pipe:/openconnect-pipe
    restart: always

  meilisearch:
    image: getmeili/meilisearch:v1.12
    environment:
      MEILI_MASTER_KEY: $MEILISEARCH_KEY
    ports:
      - "7700:7700"
    networks:
      - insa-utils
    volumes:
      - "/mnt/insa-utils-meili-data:/meili_data"

networks:
  insa-utils:
    name: insa-utils
  traefik:
    external: true
    name: traefik
  mysql:
    external: true
    name: mysql
